import React from 'react';
import Head from 'next/head'

const index = () => {
  return (
    <Head>
      <title>Feel Track</title>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://firebasestorage.googleapis.com/v0/b/feel-track.appspot.com/o/logo.jpg?alt=media&token=c3ebabe5-fd43-4e41-8bab-427643c8ab69"
      />
    </Head>
  );
}

export default index;
