import React from 'react';
import Head from 'next/head'

const index = () => {
  return (
    <Head>
      <title>Feel Track</title>
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://firebasestorage.googleapis.com/v0/b/feel-track.appspot.com/o/logo-dark.svg?alt=media&token=4a5dd9d0-26ce-4644-b1eb-aaa79f978c07"
      />
    </Head>
  );
}

export default index;
