import Head from 'next/head'

//Styles
import styles from "./page.module.scss";
import buttonStyles from '../public/scss/button.module.scss'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Feel Track</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline flex justify-center">Hello world!</h1>
      <div
        className={`flex flex-col md:flex-row justify-center items-center ${styles.page}`}
      >
        <a
            className={`${buttonStyles.secondaryButton}`}
            href={`/`}
          >
            Feel Track
        </a>
      </div>
    </div>
  );
}
